spring:
  application:
    name: UberBookingService

  datasource:
    url: jdbc:mysql://localhost:3306/uber_dblocal
    username: root
    password: Bangbang@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

